DROP DATABASE IF EXISTS ChatApp;

CREATE DATABASE IF NOT EXISTS ChatApp;
USE ChatApp;

CREATE TABLE ChatApp.User
(
	UserId INT(5) NOT NULL AUTO_INCREMENT,
	Username VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	PRIMARY KEY (UserId)
);

CREATE TABLE ChatApp.Message
(
	MessageId INT(5) NOT NULL AUTO_INCREMENT,
	Message VARCHAR(10000) NOT NULL,
	Sender VARCHAR(100) NOT NULL,
	Recipient VARCHAR(100) NOT NULL,
	read BOOLEAN NOT NULL,
	timeSent DATE NOT NULL,
	PRIMARY KEY (MessageId)
);

CREATE TABLE ChatApp.UserMessage
(
	UserId INT(5) NOT NULL,
	MessageId INT(5) NOT NULL,
	CONSTRAINT fkUser FOREIGN KEY(UserId) REFERENCES ChatApp.User(UserId),
	CONSTRAINT fkMessage FOREIGN KEY(MessageId) REFERENCES ChatApp.Message(MessageId)
);